export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_FORGET_PASSWORD_REQUEST = 'USER_FORGET_PASSWORD_REQUEST';
export const USER_FORGET_PASSWORD_SUCCESS = 'USER_FORGET_PASSWORD_SUCCESS';
export const USER_FORGET_PASSWORD_FAIL = 'USER_FORGET_PASSWORD_FAIL';
export const USER_FORGET_PASSWORD_RESET = 'USER_FORGET_PASSWORD_RESET';

export const USER_REQUEST_RESET_PASSWORD_REQUEST =
  'USER_REQUEST_RESET_PASSWORD_REQUEST';
export const USER_REQUEST_RESET_PASSWORD_SUCCESS =
  'USER_REQUEST_RESET_PASSWORD_SUCCESS';
export const USER_REQUEST_RESET_PASSWORD_FAIL =
  'USER_REQUEST_RESET_PASSWORD_FAIL';
export const USER_REQUEST_RESET_PASSWORD_RESET =
  'USER_REQUEST_RESET_PASSWORD_RESET';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';
export const USER_RESET_PASSWORD_RESET = 'USER_RESET_PASSWORD_RESET';

export const USER_VERIFY_SIGNIN_REQUEST = 'USER_VERIFY_SIGNIN_REQUEST';
export const USER_VERIFY_SIGNIN_SUCCESS = 'USER_VERIFY_SIGNIN_SUCCESS';
export const USER_VERIFY_SIGNIN_FAIL = 'USER_VERIFY_SIGNIN_FAIL';
export const USER_VERIFY_SIGNIN_RESET = 'USER_VERIFY_SIGNIN_RESET';

export const USER_REQUEST_SIGNIN_REQUEST = 'USER_REQUEST_SIGNIN_REQUEST';
export const USER_REQUEST_SIGNIN_SUCCESS = 'USER_REQUEST_SIGNIN_SUCCESS';
export const USER_REQUEST_SIGNIN_FAIL = 'USER_REQUEST_SIGNIN_FAIL';

export const USER_ADDRESS_MAP_CONFIRM = 'USER_ADDRESS_MAP_CONFIRM';
